version: '3.8'
services:
  backend:
    build: 
      context: ./backend
    ports:
      - ${PORT_BACK}:${PORT_BACK}
    volumes:
      - ./backend:/usr/app
    env_file:
      - ./.env
    depends_on:
      - mysqldb
  frontend:
    build:
      context: ./frontend
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./frontend:/usr/app
    env_file:
      - ./.env
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: